# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kioshi Pictures
email: mail@kioshi.pictures
description: > # this means to ignore newlines until "baseurl:"
  The Kioshi Picture Company is a clever young picture house in New Orleans.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kioshi.pictures" # the base hostname & protocol for your site

# Build settings
markdown: kramdown